name: GitHub Actions Practica
on: push
jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest  
    steps:
    - run: echo "El flujo de trabajo está siendo ejecutado en el evento: \"${{ github.event_name }}\""
    - run: echo "El trabajo se está ejecutando en un servidor ${{ runner.os }} hospedado en Github"
    - run: echo "El nombre de la rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}"
    - name: Verifica el código del repositorio
      uses: actions/checkout@v2
    - run: echo "el repositorio ${{ github.repository }} ha sido clonado al runner."
    - run: echo " El flujo de trabajo está listo para verificar el código en el runner."
    
    - name: Listar archivos en el repositorio para verificar el código
      run : ls ${{ github.workspace }}
      
     is_success = set (github.workspace || job.status)
     
     -run :echo"el estado del trabajo es:${{ job.status }}"
